env:
  global:
  - secure: UKidBnsjG976Pfg2NEc90Vo6oSzxsejks63rffWCF9VCvpXghewvut4fu8kRw5SRyf1mc3pMxqBIsGgDRPtSFZo7JzxgNsZLWG80bOemlSt096hlff3/2iKU8JOJfrYKvlHW4l8EV/hb2j2WBFQxfPS5Zj6c/rPzHOg7yyfMpYha2SmPFWyaYH6I+Ktc02NBbv1muqqSz8AHteODSdCvXlt2L8LWlMBDb76x/rPPP817ue0tvGotuIrxW9YJNmAn2iLhywYkWTeVck4Rfvz9BS6O+sDupzZWoONZ3Zc0be/ce5WWuaBdQV58fSWDwBFuoxUGP5Z5OcckwVI6ZjhWLD97XzSju55xMvcEMGnmVLGfKS5vw6jK/O46rSbkx96XShkYy0drfVVcTH/yNqyCVkaAB64lXWvo8dVOzI/cfHqdGKUoYWCsV294SrIrnNDGujN/nmWsfVrOOCQupbFwtExRrLD+o5eSwURl6H6r2jDExMnpO5K5zukVreEibuJV16PNvYINWfNyFGwqIsI1VZopbPlQI7Y8vI7Bd9Jsr11fs/0plTHuDRIsdDlOKy6Y1qzhionzb4BCGSe7caP3eZs9n5gWJlVknfGoxU/1YI57tx3/OlVKssrm5HMthGtDVy1tOJYBo9oD6KHCT+HhekOTRlv/6sYreyFGNqHU6l4=
  - GIT_NAME: Travis CI
  - GIT_EMAIL: mitchellkrog@gmail.com
  - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Add_Spam
  - GIT_BRANCH: master
language: python
python:
- '3.6'
matrix:
  fast_finish: true
cache:
- apt
- pip
sudo: required
before_install:
- sudo apt-get -y install python3-pip
- sudo apt-get -y install dos2unix
- pip3 install colorama
script:
- export TRAVIS_BUILD_DIR=${TRAVIS_BUILD_DIR}
- export GH_TOKEN=${GH_TOKEN}
- export TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG}
- export GIT_BRANCH=${GIT_BRANCH}
- export GIT_EMAIL=${GIT_EMAIL}
- export GIT_NAME=${GIT_NAME}
- python3 ./update.py
notifications:
  email: false
