env:
  global:
    - secure: D+cUClNzsVANTKPwG1I5D3dr9Den2xbcRYTfUFY7zRC3Y0rIR0SNBraA8uP4U7u0rvHmbNUv03XfIuSToqMlRPNKqBghmiK1vXzlWZ8UVfAPQjZhimEoncoVEB/3f85bpzWcaidlJv4/ghDTWSVXkF44UFc14E1jePGWlBXDe0/BfwNsWh6Ht/Xhu44e6FRKVOlcB5O3T7m87UzRSVgdnagL5OfKUZZx4aLguRxPDpZFrkr5n8sp7lBlPSj15kabzW3uZUesqGsuWkqm8t6OHxelps1lEUwPQ7ixRx/zmyJflgLTVWJBXqtnIEk5kG8k7F+P63QytYV2KpW7BhJh6phKpCGdNwcq5FjzX3dLvwKu/5uwkAtI+ZxqXKrf3jW64BX/liX20qthEOoYiMVXtVv7m/ASd9pi3kz8aDgZG/Rri04FHm1OjmNhr40mKPmge59FWh6/zIRmgTKbTtQGrZ7IWM1ghzqlLDGest5EXHhgkjPHmnKp9zqZTvBESTvM1qrJwniGRYC4643NRg7H+wZs4k9XVv90JVPAWdeu/YxAuKdb/Z0/lsK7j4Urhg0BFBzcrGCu5U+Y5s4WMwj4wVWQkwFXShP2WYfEOXRJYAYazXoNAG6kCU+jQeA1QxLTjayFyCOm1KT60rAQbaGbcJfCTSqYaWF8mXuJSbja0PE=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Add_Spam
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
