env:
  global:
  - secure: aTjX3U70WaAe6P+lGg00BGzk6DVGshss2mFh8nPCyLkOixSmOa/fab6TVzZOAHO6CIxY2EB+vYbSad0m28jEG44Bev7PZTGSZBeIsF/Vm8lS/87Hn9Skf8oIXWgI/cuBOUQpfRtOU6YSS+w62Zy02AIel0VVLDTi9shpeBDJlMo4D3d9PoFOnRrN4n7Yht8oA/nL7hBfCyBNNdw9k8fH1O+p1hvpz4IhCmCdUlGsfp3UvThcU67o+Vm+LFLwcEb4I/xj2MhpLXkvdvMPbLUhnt7ZmMghvjQH6ujKIVxbjlQ99xg6WxOXINN6MIN1qEIz2JujDbV2gknQ2oC+BYSiM1vCf+UFYxt8QHrjtDpjiubn9pI0g9oQ3+aCAMQwLlzjT/aXF24xMe+WPp544QK2xmlyafJT/pkkKyl1JetlTRoQMmcPhXm1hUqWGqsaSvrvcYZlRypWHDDDwWg2v/VB5+fkkPIZkAzOVvLccet08gIum1awbGkaTmNTWmv3rAlJdvPFuWPyrBH4YEJoo7R6rpAFEBQiM6XCOiAxlDJSCzjbGt5f6VVyDXpx3NhxoLxXRxSJFOQYJnEiiWr5BW6p34qydH9N8Rrtd6VS08ir4snup0qSYGr/VXRU1q+O0ITY3YChE6BRHLVD68E7Jovi+7FN6fFnwb/U8249JNWTshE=
  - GIT_NAME: Travis CI
  - GIT_EMAIL: mitchellkrog@gmail.com
  - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Add_Spam
  - GIT_BRANCH: master
language: python
python:
- '3.6'
matrix:
  fast_finish: true
cache:
- apt
- pip
sudo: required
before_install:
- sudo apt-get -y install python3-pip
- sudo apt-get -y install dos2unix
- pip3 install colorama
script:
- export TRAVIS_BUILD_DIR=${TRAVIS_BUILD_DIR}
- export GH_TOKEN=${GH_TOKEN}
- export TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG}
- export GIT_BRANCH=${GIT_BRANCH}
- export GIT_EMAIL=${GIT_EMAIL}
- export GIT_NAME=${GIT_NAME}
- python3 ./update.py
notifications:
  email: false
