env:
  global:
    - secure: EkIzy8Lab7LQzYgze+R8ppStVZxPLU5zzShwEi/uEFPBt9SAn/+FvV//JsfZFHnS/O4DLHAoRVqORiAxwDhZYrdVVaQtchzCiRnXwH0PEMWIT8focnKEeORlBYDHExcTmKcfqs1htRskOx+zBnLaVwYPLfxEencZDr+ORymBG1NXGKUq7tnZps3yUthdN9uXB6xgkrbI66k7G0UKrsNnfzQZPvtF3LgKma8hDvkSYGx7aspjWlnebGGDBlHVxDftVPl+1HraHJjOAHpxuGU7+C1IJjTAdgPZkiL1r4avFJbYVISzcQJrCwa2nvM9hal+DpnJwRVHs9ZxctQWnfm+BH3j1NvPD/PT/sMkkqZNdeUKs5Wy/sr1sMKPL8mLR+GzRwOdhjgrtJ91Gxx2xtybT490O82AT/YMuZYNuoDyUq7uAP+g14bMki7FGllks8Kq8pqISxlzpQ5w6LIcx4RChCe7PTIKZfw6UNwLPNLqzsKoqBJmE31iHMAQ1r6ebm8tSpTDuQei+HdM5vORVBVqCOP/9rUiCcvO5CdrkkcWO9cNKgO062Iqq6V2UDsTjB+kvit/XUjXUjL8F6TJOOXNR+2MNvbwcMMiL1B9ckaB00o97hOr2ONMx+P6z2fQG8Ic1NoOaWm8EnnsE3WIz5Bn+slLbmZbx6lJF5O+HpmRhjg=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Add_Spam
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
