env:
  global:
  - secure: lmm5eubd1IamxUGrMss14rycrj8QFUHBq24/oJ2Itc+KHM6fwBGWVHLbzmpGBfLV2OB54IzFKrjyWcL5nrV7lqUyZHZ2z9Tp5w+muPq8MR4t9zNBkWWlXuzQn5qaGN2KfUe5USPABSpxob79KS2nKFEuIcjVcWzDXZO9h1pQJZiSRD25tVbesoAwuKrxImHkf7hU9ytE34tTlTisvF47kqb8CHrDmJ7opopAsUTVZxGVAdDP7w47hfWqNJo7uazWp+RKfQgVZ+M3XP43o9S/6j/R9N8IgiqtHoTETe3L1S+lr2F/Nws/zWb9xWxvfrnjAYJxd2S80o48NjJm12/TKtNLle4GCnqF+FO1rvEiXVTaRZkYAelDz+0AsfgYF88CYUFGcjCvwIIS44/ZH53EgNOAlNdeji0QvLom75z8awbtLupU9BpGWQvGmSTIQ2ojXI0S4jNyQ32M+IRqAxHwxxYteJQwP3f35i3DO7T6lTTjw2btZM78rgmMcA+btdwVoXA7chYCz+gzkwv6MLEVFad501JBj1igMkbqxRWXtJPBkhBQhYm92dOHbOW6ELVb/ogOkICjdYtTfnP0aIyorxetyRdEY6y0OLTs24RzlBIJz7LsuGnlUMi7hMHIcTd/x4Jg2aVcYCp2JOamEE/fqaVXYG/MsKARPzDAVjKEbzk=
  - GIT_NAME: Travis CI
  - GIT_EMAIL: mitchellkrog@gmail.com
  - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Add_Spam
  - GIT_BRANCH: master
language: python
python:
- '3.6'
matrix:
  fast_finish: true
cache:
- apt
- pip
sudo: required
before_install:
- sudo apt-get -y install python3-pip
- sudo apt-get -y install dos2unix
- pip3 install colorama
script:
- export TRAVIS_BUILD_DIR=${TRAVIS_BUILD_DIR}
- export GH_TOKEN=${GH_TOKEN}
- export TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG}
- export GIT_BRANCH=${GIT_BRANCH}
- export GIT_EMAIL=${GIT_EMAIL}
- export GIT_NAME=${GIT_NAME}
- python3 ./update.py
notifications:
  email: false
