env:
  global:
    - secure: Kcgt6wX8f4sU5e4Oe2649VJeZOhjxFsSsupR35gZX78z7S3S9i/yVKK1g5Zt14OCQo7dtCYhIkgUV10ovRBXqhDMBVaS+JQ5HuB+gKYOMTt6wjVmvzaA48FjGKc5s4NDLl8fZflKMvkuTYYyQfeFmgI1BACdIvXa/fsiiRjt0VjCkaVJrewAqBLEFr8GC99S3Vpw3o52WsHK8Ll5P8UhKfEphc+VwzHwfEAXG4HUWegNNjaE/karS5BSQpnN5N1Q8U1axb/Jww1RK3dEBRIrJRJzvhwPA95Bz/sUkC74CdZ62yIvOteqIvcvlA3Z2xAFhmUvyyfYN7gAObodnzmPBlqjrfMsnwpbN34iMn8SE2B/z4klvX6eIzqMIvMEekKSMcgfDN9zkzEvwfNjL8PwMV9qCAafVdCDISDY7t5gYfdgNnfByCHSURcXgTdctn+S5lpUChy2MVOmUAFIhvRd1PhW0LDGUFmCneVM7nc1k3cG8A5pyYjX+qZ30+dhGkm0glLBHDQBIer8RFdl/Jp+XdsoNANeRQZPS+rN86zcyywZJdm2pCRVM1Q8Zl+DHwMD6b0BT2TBw9v9jDe6q8lEFSOcr2y0vz4ncc+OPGjI9oCUMT15JteypYOEmeUV3QUl5nW/6L7gFIB8UaI/NloJXwxQqK7Dn2b2vqr0DuCihYA=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/Add_Spam
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
